{% set version = "0.18.1" %}
{% set WIN_FLEX_BIZON_VERSION = "2.5.20" %}
{% set LIBEVENT_VERSION = "2.1.8" %}

package:
  name: thrift-split
  version: {{ version }}

source:
  - url: http://archive.apache.org/dist/thrift/{{ version }}/thrift-{{ version }}.tar.gz
    sha256: 04c6f10e5d788ca78e13ee2ef0d2152c7b070c0af55483d6b942e29cff296726
    patches:
      - patches/0001-windows-fixes.patch  # [win]
  {% if win %}
  - url: https://github.com/lexxmark/winflexbison/releases/download/v{{ WIN_FLEX_BIZON_VERSION }}/win_flex_bison-{{ WIN_FLEX_BIZON_VERSION }}.zip
    folder: thirdparty\dist\winflexbison
  - url: https://github.com/nmathewson/Libevent/archive/release-{{ LIBEVENT_VERSION }}-stable.zip
    folder: thirdparty\src\libevent
  {% endif %}

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - bison           # [unix]
    - cmake
    - flex            # [unix]
    - pkg-config      # [unix]
    - ninja
  host:
    - boost-cpp
    - libevent
    - openssl
    - zlib
  run:

outputs:
  - name: libthrift
    script: install.sh   # [unix]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - bison           # [unix]
        - cmake
        - flex            # [unix]
        - pkg-config      # [unix]
        - ninja
      host:
        - boost-cpp
        - libevent
        - openssl
        - zlib
    test:
      requires:
        # cmake needs compiler to be able to run package detection, see
        # https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
        - {{ compiler('cxx') }}
        - cmake
        - ninja
      files:
        - cmake_test/
      commands:
        # presence of shared libs
        - test -f $PREFIX/lib/libthrift.so                      # [linux]
        - test -f $PREFIX/lib/libthrift.dylib                   # [osx]
        - if not exist %LIBRARY_BIN%\thriftmd.dll exit 1        # [win]
        - if not exist %LIBRARY_LIB%\thriftmd.lib exit 1        # [win]

        # absence of static libs
        - test ! -f $PREFIX/lib/libthrift.a                     # [unix]

        # absence of binaries
        - test ! -f $PREFIX/bin/thrift                          # [unix]
        - if exist %LIBRARY_BIN%\thrift.exe exit 1              # [win]

        # presence of headers
        - test -f $PREFIX/include/thrift/Thrift.h               # [unix]
        - if not exist %LIBRARY_INC%\thrift\Thrift.h exit 1     # [win]

        # test CMake integration, i.e. find_package(thrift)
        - cd cmake_test
        - cmake -GNinja $CMAKE_ARGS .   # [unix]
        - cmake -GNinja %CMAKE_ARGS% .  # [win]

  - name: thrift-compiler
    script: install.sh   # [unix]
    script: install.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - bison           # [unix]
        - cmake
        - flex            # [unix]
        - pkg-config      # [unix]
        - ninja
      host:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - boost-cpp
        - libevent
        - openssl
        - zlib
      run:
        - {{ pin_subpackage("libthrift", exact=true) }}
    test:
      commands:
        # presence of binaries
        - test -f $PREFIX/bin/thrift                    # [unix]
        - if not exist %LIBRARY_BIN%\thrift.exe exit 1  # [win]

  - name: thrift-cpp
    build:
      run_exports:
        - {{ pin_subpackage("libthrift", max_pin="x.x.x") }}
    requirements:
      host:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - {{ pin_subpackage("thrift-compiler", exact=true) }}
      run:
        - {{ pin_subpackage("libthrift", exact=true) }}
        - {{ pin_subpackage("thrift-compiler", exact=true) }}
    test:
      commands:
        - echo "tested in other outputs"

about:
  home: http://thrift.apache.org
  license: Apache-2.0
  license_file: LICENSE
  summary: >-
    Compiler and C++ libraries and headers for the Apache Thrift RPC system
  dev_url: https://github.com/apache/thrift

extra:
  recipe-maintainers:
    - wesm
    - msarahan
    - jakirkham
    - xhochy
    - h-vetinari
  feedstock-name: thrift-cpp
